CREATE TABLE IF NOT EXISTS public."Armor"

{
      "code": 201102,
      "name": "모자",
      "modeType": 0,
      "itemType": "Armor",
      "armorType": "Head",
      "itemGrade": "Common",
      "isCompletedItem": false,
      "markingType": "None",
      "craftAnimTrigger": "craftMetal",
      "stackable": 1,
      "initialCount": 1,
      "itemUsableType": "EXCEPT",
      "itemUsableValueList": 51,
      "exclusiveProducer": 0,
      "canNotBeTakeItemFromCorpse": false,
      "makeMaterial1": 0,
      "makeMaterial2": 0,
      "notDisarm": false,
      "manufacturableType": 1,
      "attackPower": 0,
      "attackPowerByLv": 0,
      "defense": 4,
      "defenseByLv": 0,
      "skillAmp": 0,
      "skillAmpByLevel": 0,
      "skillAmpRatio": 0,
      "skillAmpRatioByLevel": 0,
      "maxHp": 0,
      "maxHpByLv": 0,
      "maxSp": 0,
      "hpRegenRatio": 0,
      "hpRegen": 0,
      "spRegenRatio": 0,
      "spRegen": 0,
      "attackSpeedRatio": 0,
      "attackSpeedRatioByLv": 0,
      "criticalStrikeChance": 0,
      "criticalStrikeDamage": 0,
      "preventCriticalStrikeDamaged": 0,
      "cooldownReduction": 0.02,
      "cooldownLimit": 0,
      "lifeSteal": 0,
      "normalLifeSteal": 0,
      "skillLifeSteal": 0,
      "moveSpeed": 0,
      "sightRange": 0,
      "moveSpeedOutOfCombat": 0,
      "attackRange": 0,
      "increaseBasicAttackDamage": 0,
      "increaseBasicAttackDamageByLv": 0,
      "preventBasicAttackDamaged": 0,
      "preventBasicAttackDamagedByLv": 0,
      "preventBasicAttackDamagedRatio": 0,
      "preventBasicAttackDamagedRatioByLv": 0,
      "increaseBasicAttackDamageRatio": 0,
      "increaseBasicAttackDamageRatioByLv": 0,
      "preventSkillDamaged": 0,
      "preventSkillDamagedByLv": 0,
      "preventSkillDamagedRatio": 0,
      "preventSkillDamagedRatioByLv": 0,
      "penetrationDefense": 0,
      "penetrationDefenseRatio": 0,
      "trapDamageReduce": 0,
      "trapDamageReduceRatio": 0,
      "hpHealedIncreaseRatio": 0,
      "healerGiveHpHealRatio": 0,
      "uniqueAttackRange": 0,
      "uniqueHpHealedIncreaseRatio": 0,
      "uniqueCooldownLimit": 0,
      "uniqueTenacity": 0,
      "uniqueMoveSpeed": 0,
      "uniquePenetrationDefense": 0,
      "uniquePenetrationDefenseRatio": 0,
      "uniqueLifeSteal": 0,
      "uniqueSkillAmpRatio": 0,
      "restoreItemWhenResurrected": true
    }

    TABLESPACE pg_default;

    ALTER TABLE IF EXISTS public."Armor"
        OWNER TO postgres; 